# Generated by Django 3.2.4 on 2021-07-11 05:19

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dataset_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(default='')),
                ('upload', models.FileField(upload_to=api.models.data_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'h5'])])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
