# Generated by Django 3.2.4 on 2021-07-14 12:30

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_neuralnetworkmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworkmodel',
            name='dataset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.dataset'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkmodel',
            name='upload',
            field=models.FileField(upload_to=api.models.model_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
