# Generated by Django 3.2.4 on 2021-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210714_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworkmodel',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
